
/* ===== GUIA (conteudo pesquisado; numeros revisados) ===== */
var GUIA = [
  {id:'raiox', t:'Raio-x: 30 dias lançando tudo + lista das dívidas', o:'Por 30 dias, lança cada gasto no app no mesmo dia, com a conta ou o cartão de origem. Em paralelo, cadastra cada dívida na Planilha: credor, saldo, juros ao mês, parcela e se está no rotativo ou no cheque especial.', why:'Ninguém corta o que não vê. E dívida só se ataca em ordem quando está toda na mesa.', crit:'30 dias seguidos sem gasto do extrato faltando no app, e todas as dívidas cadastradas.', ev:'moderada'},
  {id:'prolabore', t:'Separar PF de PJ e fixar o pró-labore no piso', o:'Tudo que a agência recebe entra na conta PJ; todo custo da agência sai dela. Você recebe um pró-labore fixo, no mesmo dia todo mês. O valor é o PISO: o 3º menor mês dos últimos 12, não a média. O INSS sobre o pró-labore é o seu piso de aposentadoria e de auxílio-doença: pra quem vive de PJ, ficar doente é renda zero.', why:'A média descreve o ano, não descreve nenhum mês. O piso é o único número que cabe em todo mês.', crit:'2 meses seguidos de pró-labore no mesmo valor e na mesma data, sem gasto pessoal no cartão da PJ.', ev:'convenção'},
  {id:'planilha', t:'Planilha: essenciais cabem no pró-labore', o:'Na aba Planilha, a entrada prevista é o pró-labore (o piso). Os essenciais têm que caber dentro dele. Gasto anual (IPVA, IPTU, seguro, DAS) entra dividido por 12, senão o mês do IPVA vira uma sobra negativa falsa. O que a PJ ganhar acima do piso fica na PJ como "conta de nivelamento", que paga o pró-labore inteiro no mês fraco.', why:'É assim que renda variável vira renda previsível: o mês bom banca o mês ruim em vez de virar gasto.', crit:'Conta de nivelamento com pelo menos 1 pró-labore guardado e 3 meses com essenciais ≤ 100% do pró-labore.', ev:'convenção'},
  {id:'friccao', t:'Cartão fora do alcance', o:'Apaga o cartão salvo em todos os apps e lojas. Desliga compra com 1 clique. Dia a dia no débito ou Pix. Baixa o limite do cartão pra no máximo 1 pró-labore. Descadastra de todo e-mail e notificação de promoção.', why:'Quem tem disciplina não resiste mais: evita a tentação. E-mail de promoção aumentou o gasto em 37% em 70 experimentos.', crit:'4 semanas seguidas com besteira ≤ 5% da renda, cartão apagado dos apps e limite reduzido.', ev:'forte'},
  {id:'depois', t:'Lista do Depois (72h)', o:'Vontade de comprar algo que não é essencial? Anota nome e valor, sem se proibir, e decide na revisão de sexta. "Depois", nunca "nunca".', why:'Adiar sem data reduziu o desejo mais do que a proibição, em 4 experimentos. Na sexta, a maioria já não faz sentido.', crit:'Uma semana inteira sem compra não essencial no impulso.', ev:'moderada'},
  {id:'rotativo', t:'Estancar: sair do rotativo e do cheque especial', o:'Nunca paga o mínimo da fatura. Se não dá pra pagar inteira: parcela a fatura no próprio banco, ou pede portabilidade do saldo pra outro banco com juro menor. Zera o limite do cheque especial.', why:'Rotativo passa de 400% ao ano, o crédito mais caro do país. Nenhum investimento chega perto: pagar essa dívida É o melhor investimento que existe.', crit:'Saldo zero em rotativo e cheque especial, e nenhuma fatura paga no mínimo por 3 meses.', ev:'forte'},
  {id:'colchao', t:'Colchão de choque: meio mês de essenciais', o:'Antes de atacar o resto das dívidas, guarda meio mês de custo essencial em Tesouro Selic ou CDB de liquidez diária (100% do CDI ou mais, dentro do FGC), em conta separada da que paga as contas. Marca como "reserva" na aba Investir.', why:'O choque de gasto típico equivale a meio mês de despesas. Sem esse colchão, todo imprevisto volta pro rotativo.', crit:'Meio mês de custo essencial em ativo líquido, em conta separada, mantido por 60 dias.', ev:'moderada'},
  {id:'dividas', t:'Negociar e quitar o resto, em ordem', o:'Dívida atrasada: Serasa Limpa Nome (grátis), canal do banco, feirão vigente. Ordem de ataque: a de juros mais alto primeiro; entre parecidas, a menor, pra fechar contas e ganhar fôlego. Parcelas somadas ≤ 35% do pró-labore. Se não fecha a conta de jeito nenhum: a Lei do Superendividamento (14.181/2021) permite repactuar todas as dívidas de consumo numa audiência única, pelo Procon ou pela Defensoria, com plano de até 5 anos.', why:'Fechar contas prevê a quitação total (dados de 6 mil pessoas num programa de dívidas). Mas juro alto custa mais que motivação: olha a taxa primeiro.', crit:'Toda dívida com acordo formalizado, parcelas ≤ 35% do pró-labore e nenhuma dívida nova em 90 dias.', ev:'moderada'},
  {id:'automatico', t:'Pague-se primeiro, automático', o:'No dia em que o pró-labore cai, uma transferência agendada leva uma porcentagem fixa pra reserva antes de qualquer gasto. Começa com o que couber (5 ou 10%) e sobe 2 a 3 pontos a cada mês bom.', why:'Poupança automática, tirada antes do gasto e aumentada aos poucos, é o que a evidência mostra que funciona (Thaler & Benartzi). "Guardar o que sobrar" não sobra.', crit:'Transferência automática rodando há 3 meses e sobra ≥ 10% em cada um.', ev:'forte'},
  {id:'reserva', t:'Reserva em degraus: 3, 6, 12 meses', o:'Com rotativo zerado e dívidas em acordo, o excedente vai pra reserva até 3 meses de custo essencial. Depois 6. Como a sua renda varia, o alvo final é 12. Onde: Tesouro Selic ou CDB de liquidez diária. Nunca poupança.', why:'Reserva é o que segura o mês fraco sem virar dívida. Renda variável pede mais degraus que salário fixo.', crit:'Degrau 1: 3 meses. Degrau 2: 6. Degrau 3: 12. O app mostra em qual você está.', ev:'moderada'},
  {id:'investir', t:'Só agora: investir com escada de risco', o:'Com 6 meses de reserva e zero dívida cara, cria um segundo aporte automático mensal. Ordem sensata: Tesouro IPCA+ ou CDB de prazo pra objetivo com data; depois ETF de índice amplo; FII e ações depois; cripto por último e pequeno.', why:'Investir com dívida cara é enxugar gelo. Investir sem reserva vira resgate no primeiro aperto. Fundo ativo perde do índice na maioria dos casos em 10 anos (SPIVA).', crit:'Aporte automático de investimento há 3 meses, com a reserva intacta.', ev:'forte'},
  {id:'revisao', t:'Revisão semanal de 15 min e fechamento do mês', o:'Toda semana, dia fixo: confere o extrato de cada conta contra o app, categoriza o que ficou solto, marca "me arrependo" com honestidade e olha os indicadores. No fim do mês: recalcula o piso e copia o resumo pro check-in.', why:'Monitorar o progresso aumenta a chance de bater a meta (meta-análise com 138 estudos). Hora marcada tira a decisão de "olhar ou não".', crit:'8 revisões semanais seguidas e 2 fechamentos de mês.', ev:'forte'},
  {id:'numero', t:'O número da independência', o:'Custo anual de vida desejado (essencial + variável, sem besteira) × 25. Esse é o patrimônio de referência pra viver de renda. Anota e acompanha o % atingido na aba Investir.', why:'Meta sem número não vira aporte. Com número, cada mês tem um pedaço de progresso visível.', crit:'Número registrado e percentual atingido acompanhado a cada fechamento.', ev:'convenção'}
];
var INDIC = [
  {t:'Sobra do mês', f:'(entrou − saiu) ÷ entrou', d:'Verde de 20% pra cima (regra 50/30/20: 20% pra poupança e dívida). Âmbar de 10 a 20. Vermelho abaixo de 10. Com renda variável, o que entra é o pró-labore; o excedente fica na PJ. Enquanto houver dívida cara, pagar a mais conta como sobra.'},
  {t:'Custo essencial', f:'essenciais da planilha ÷ renda base (o piso, quando houver 3+ meses de ganhos)', d:'Verde até 50% (a fatia "necessidades" da 50/30/20). Âmbar até 70. Vermelho acima: sobra menos de 30% pra tudo o mais, e qualquer mês fraco vira dívida.'},
  {t:'Reserva', f:'investimentos marcados como reserva ÷ custo essencial mensal', d:'Vermelho abaixo de meio mês (o choque de gasto típico equivale a meio mês de despesas; ter isso guardado se associa a mais bem-estar financeiro). Âmbar de meio a 6 meses (3 a 6 é a faixa clássica dos planejadores). Verde de 6 pra cima; com renda variável, o alvo é 12.'},
  {t:'Besteira', f:'gastos marcados "me arrependo" ÷ entrou', d:'Verde até 5%. Âmbar de 5 a 10. Vermelho acima de 10. Não existe benchmark publicado: é convenção do app, derivada da fatia "desejos" da 50/30/20. Depende da sua honestidade na hora de lançar.'},
  {t:'Dívidas', f:'parcelas + mínimos + juros do mês ÷ entrou', d:'Verde até 20%. Âmbar de 20 a 35 (35% é a margem legal do consignado). Vermelho acima. E qualquer saldo em rotativo ou cheque especial pinta vermelho, independente do percentual.'}
];
var MITOS = [
  ['"Poupança é segura e rende bem."', 'Com a Selic acima de 8,5% ao ano, a poupança rende 0,5% ao mês + TR por regra do Banco Central. Tesouro Selic e CDB de liquidez diária rendem mais com a mesma liquidez.'],
  ['"Parcelado sem juros não custa nada."', 'O custo está no preço: quem paga à vista subsidia quem parcela. E parcelar aumentou o gasto total nos experimentos, não só adiou.'],
  ['"Pagar o mínimo do cartão resolve por enquanto."', 'O mínimo joga o resto no rotativo, o crédito mais caro do país. Parcelar a fatura ou pedir portabilidade custa uma fração disso.'],
  ['"Limite do cartão e cheque especial são dinheiro meu."', 'São crédito pré-aprovado com juros de dois a três dígitos ao ano.'],
  ['"Depois de 5 anos a dívida some."', 'O nome sai do cadastro negativo e para de afetar o score, mas a dívida continua existindo e pode ser cobrada.'],
  ['"Guardo o que sobrar no fim do mês."', 'Não sobra. A evidência é o contrário: poupança automática, tirada antes do gasto e aumentada aos poucos.'],
  ['"Preciso de muito dinheiro pra começar a investir."', 'No Tesouro Direto o mínimo é 1% de um título (de uns R$ 5 a uns R$ 200). E o Tesouro Reserva aceita a partir de R$ 1.'],
  ['"Renda fixa nunca perde."', 'Tesouro IPCA+ e Prefixado sofrem marcação a mercado: se os juros sobem e você vende antes do vencimento, o preço cai. Só quem segura até o fim recebe o combinado.'],
  ['"Bitcoin pode ser minha reserva."', 'Já caiu 77% do topo em 2022, 84% em 2018, 86% em 2015. Reserva é o que não cai no mês em que você precisa dela.'],
  ['"Dá pra viver de day trade."', 'Estudo FGV/CVM com todos os operadores de minicontratos entre 2012 e 2017: a imensa maioria dos que insistiram perdeu dinheiro.'],
  ['"Gestor profissional bate o índice."', 'Nos scorecards SPIVA da América Latina, em 10 anos a maioria dos fundos ativos perdeu do índice.'],
  ['"Não dá pra fazer orçamento com renda variável."', 'Dá, trocando a média pelo piso: os fixos cabem no 3º menor mês dos últimos 12, e o excedente dos meses bons vira conta de nivelamento.'],
  ['"É só ganhar mais."', 'A pesquisa que deu origem à 50/30/20 nasceu observando famílias quebrando com a renda subindo. Ganhar mais sem estrutura vira gasto.']
];
var CLASSE_INFO = {
  rf:'Tesouro Selic (mínimo de 1% de um título, uns R$ 200; resgate cai no mesmo dia se pedido até 13h em dia útil; o devedor é o governo) é o padrão da reserva. O Tesouro Reserva rende o mesmo e aceita a partir de R$ 1. CDB: só com liquidez diária e 100% do CDI ou mais, dentro do FGC (R$ 250 mil por CPF por banco). LCI/LCA: isentas de IR, mas presas até o vencimento; nunca pra reserva. Tesouro IPCA+/Prefixado: só pra objetivo com data, porque oscilam se você vende antes.',
  fii:'Fundos que compram imóveis ou títulos imobiliários e distribuem aluguel mensal, isento de IR. A cota cai quando os juros sobem; vacância corta o rendimento. Depois da reserva e do ETF de índice, e diversificando entre fundos e setores.',
  acao:'Pedaços de empresas na B3. Quedas de 30 a 50% acontecem. Pra quem está começando: ETF de índice amplo com aporte automático, horizonte de 5 anos ou mais. Só com reserva completa e zero dívida cara.',
  rv:'ETFs, fundos multimercado, BDRs. Mesma regra das ações: prazo longo, aporte automático, e só depois da reserva.',
  cripto:'Sem emissor e sem fluxo de caixa: o retorno depende só do próximo comprador. Quedas do topo de 77% a 93% no histórico. Por último, pequeno, e com o que você aguenta perder quase todo sem mudar a vida. Jamais como reserva.'
};
