# -*- coding: utf-8 -*-
import io, json
def rd(p): return io.open(p, encoding='utf-8').read()
def wr(p, s): io.open(p, 'w', encoding='utf-8', newline='\n').write(s)
def patch(path, pairs):
    s = rd(path)
    for a, b in pairs:
        assert s.count(a) == 1, (path, a[:70], s.count(a))
        s = s.replace(a, b)
    wr(path, s)

# ---- CSS ----
patch('src/A-head.html', [
 ('.dayhead{font-family:var(--mono);font-size:12px;color:var(--muted);text-transform:uppercase;letter-spacing:.06em;padding:14px 0 2px;display:flex;justify-content:space-between}',
  '.dayhead{font-family:var(--mono);font-size:12px;color:var(--muted);text-transform:uppercase;letter-spacing:.06em;padding:14px 0 4px;display:flex;justify-content:space-between;position:sticky;top:0;background:var(--bg);z-index:2}\n'
  '.stack{display:flex;height:10px;border-radius:10px;overflow:hidden;background:var(--surface-2)}\n'
  '.stack span{display:block;height:100%}.stack .e{background:#6F8CFF}.stack .l{background:#3ECF8E}.stack .b{background:var(--bad)}\n'
  '.stack-leg{display:flex;gap:14px;flex-wrap:wrap;font-size:12.5px;color:var(--muted);margin:6px 0 0;font-family:var(--mono)}.stack-leg i{width:10px;height:10px;border-radius:3px;display:inline-block;margin-right:5px;vertical-align:-1px}\n'
  '.ritmo{font-family:var(--mono);font-size:10px;letter-spacing:.05em;text-transform:uppercase;padding:1px 6px;border-radius:999px;margin-left:6px;white-space:nowrap}.ritmo.ok{background:var(--good-soft);color:var(--good)}.ritmo.mid{background:var(--mid-soft);color:var(--mid)}.ritmo.bad{background:var(--bad-soft);color:var(--bad)}\n'
  'details.mais{border-top:1px solid var(--line);padding-top:6px}details.mais summary{cursor:pointer;color:var(--accent);font-weight:600;font-size:14px;padding:6px 0;list-style:none;display:flex;align-items:center;gap:6px}details.mais summary::-webkit-details-marker{display:none}details.mais summary::before{content:"+";font-family:var(--mono);font-size:16px}details.mais[open] summary::before{content:"−"}details.mais > div{display:flex;flex-direction:column;gap:12px;padding-top:8px}\n'
  '.livre{display:flex;justify-content:space-between;align-items:baseline;gap:10px;margin-top:8px;padding-top:10px;border-top:1px solid rgba(255,255,255,.12)}.livre b{font-family:var(--display);font-stretch:80%;font-weight:800;font-size:22px}.livre span{font-size:13px;color:var(--muted)}.hero.pos .livre span,.hero.neg .livre span{color:rgba(242,241,251,.7)}.livre .dia{font-family:var(--mono);font-size:13px;text-align:right}'),
 ('.tx .v.g{color:var(--good)}.tx .v.r{color:var(--ink)}', '.tx .v.g{color:var(--good)}.tx .v.r{color:var(--ink)}.tx .v.t{color:var(--muted)}.tx.transf{opacity:.7}'),
])

# ---- markup: faixa empilhada acima das categorias ----
patch('src/B-body.html', [
 ('    <div class="sec-head"><h2>Onde foi o dinheiro</h2><span id="catSub"></span></div>\n    <div class="cats" id="cats"></div>',
  '    <div class="sec-head"><h2>Onde foi o dinheiro</h2><span id="catSub"></span></div>\n    <div id="stackBox"></div>\n    <div class="cats" id="cats"></div>'),
])

# ---- JS ----
patch('src/H-fin.js', [
 # tipo transferencia nao conta
 ("function lancMes(d){ var k = mesKey(d); return FIN.lanc.filter(function(t){ return t.data && t.data.slice(0, 7) === k; }); }",
  "function lancMes(d){ var k = mesKey(d); return FIN.lanc.filter(function(t){ return t.data && t.data.slice(0, 7) === k; }); }\nfunction diasNoMes(d){ return new Date(d.getFullYear(), d.getMonth() + 1, 0).getDate(); }\nfunction diaHoje(d){ var h = agora(); if(h.getFullYear() === d.getFullYear() && h.getMonth() === d.getMonth()) return h.getDate(); return h > d ? diasNoMes(d) : 0; }"),
 # sheet: 3 toques + transf + salvar e lancar outro
 ("function sheetLanc(t){\n  var novo = !t; t = t ? clone(t) : {id:uid(), tipo:'gasto', valor:0, desc:'', cat:'', conta:(FIN.contas[0] || {}).id || '', data:keyOf(midnight(agora())), arrep:false, orc:null};\n  if(!t.cat) t.cat = t.tipo === 'ganho' ? 'cliente' : '';",
  "function sheetLanc(t, outro){\n  var novo = !t; t = t ? clone(t) : {id:uid(), tipo:'gasto', valor:0, desc:'', cat:'', conta:(FIN.cfg && FIN.cfg.contaPadrao) || (FIN.contas[0] || {}).id || '', data:keyOf(midnight(agora())), arrep:false, orc:null};\n  if(!t.cat) t.cat = t.tipo === 'ganho' ? 'cliente' : (t.tipo === 'transf' ? 'transf' : '');"),
 ("    var seg = el('div', 'segctl'); var bG = el('button', null, 'Gasto'), bR = el('button', null, 'Ganho'); bG.type = bR.type = 'button'; bG.id = 'lt-gasto'; bR.id = 'lt-ganho';\n    function segSet(){ bG.setAttribute('aria-selected', t.tipo === 'gasto' ? 'true' : 'false'); bR.setAttribute('aria-selected', t.tipo === 'ganho' ? 'true' : 'false'); catBox.replaceWith(catBox = chipsDe(t.tipo === 'ganho' ? CATS_G : CATS, t.cat, function(id){ t.cat = id; }, 'lc')); arrepRow.hidden = t.tipo !== 'gasto'; orcRow.hidden = t.tipo !== 'gasto'; }\n    bG.addEventListener('click', function(){ t.tipo = 'gasto'; if(!catDe(t.cat, 'gasto') || CATS_G.some(function(c){ return c.id === t.cat; })) t.cat = ''; segSet(); });\n    bR.addEventListener('click', function(){ t.tipo = 'ganho'; t.arrep = false; t.orc = null; if(!CATS_G.some(function(c){ return c.id === t.cat; })) t.cat = 'cliente'; segSet(); });\n    seg.appendChild(bG); seg.appendChild(bR); sh.appendChild(seg);",
  "    var seg = el('div', 'segctl'); seg.style.gridTemplateColumns = '1fr 1fr 1fr'; var bG = el('button', null, 'Gasto'), bR = el('button', null, 'Ganho'), bT = el('button', null, 'Transf.'); bG.type = bR.type = bT.type = 'button'; bG.id = 'lt-gasto'; bR.id = 'lt-ganho'; bT.id = 'lt-transf';\n    var catLbl = el('p', 'mini', 'Categoria'), transfNote = el('p', 'mini', 'Pagamento de fatura, aporte na reserva, dinheiro entre contas. Não conta como gasto nem como ganho.'); transfNote.hidden = true;\n    function segSet(){ bG.setAttribute('aria-selected', t.tipo === 'gasto' ? 'true' : 'false'); bR.setAttribute('aria-selected', t.tipo === 'ganho' ? 'true' : 'false'); bT.setAttribute('aria-selected', t.tipo === 'transf' ? 'true' : 'false'); var novoBox = t.tipo === 'transf' ? el('div') : chipsDe(t.tipo === 'ganho' ? CATS_G : CATS, t.cat, function(id){ t.cat = id; }, 'lc'); catBox.replaceWith(novoBox); catBox = novoBox; catLbl.hidden = t.tipo === 'transf'; transfNote.hidden = t.tipo !== 'transf'; arrepRow.hidden = t.tipo !== 'gasto'; orcRow.hidden = t.tipo !== 'gasto'; }\n    bG.addEventListener('click', function(){ t.tipo = 'gasto'; if(CATS_G.some(function(c){ return c.id === t.cat; }) || t.cat === 'transf') t.cat = ''; segSet(); });\n    bR.addEventListener('click', function(){ t.tipo = 'ganho'; t.arrep = false; t.orc = null; if(!CATS_G.some(function(c){ return c.id === t.cat; })) t.cat = 'cliente'; segSet(); });\n    bT.addEventListener('click', function(){ t.tipo = 'transf'; t.arrep = false; t.orc = null; t.cat = 'transf'; segSet(); });\n    seg.appendChild(bG); seg.appendChild(bR); seg.appendChild(bT); sh.appendChild(seg);"),
 ("    var idesc = el('input'); idesc.type = 'text'; idesc.value = t.desc; idesc.placeholder = 'Ex.: iFood, Netflix, cliente X'; idesc.maxLength = 60;\n    idesc.addEventListener('input', function(){ t.desc = idesc.value; });\n    sh.appendChild(campo('Descrição', idesc, 'ldesc'));\n    sh.appendChild(el('p', 'mini', 'Categoria'));\n    var catBox = chipsDe(t.tipo === 'ganho' ? CATS_G : CATS, t.cat, function(id){ t.cat = id; }, 'lc'); sh.appendChild(catBox);\n    var g2 = el('div', 'grid2');",
  "    sh.appendChild(catLbl); sh.appendChild(transfNote);\n    var catBox = t.tipo === 'transf' ? el('div') : chipsDe(t.tipo === 'ganho' ? CATS_G : CATS, t.cat, function(id){ t.cat = id; }, 'lc'); sh.appendChild(catBox);\n    var idesc = el('input'); idesc.type = 'text'; idesc.value = t.desc; idesc.placeholder = 'Ex.: iFood, Netflix, cliente X'; idesc.maxLength = 60;\n    idesc.addEventListener('input', function(){ t.desc = idesc.value; });\n    var arrepRow = el('label', 'switch'); var ca = el('input'); ca.type = 'checkbox'; ca.id = 'larrep'; ca.checked = !!t.arrep; ca.addEventListener('change', function(){ t.arrep = ca.checked; });\n    arrepRow.appendChild(ca); arrepRow.appendChild(document.createTextNode('Me arrependo (besteira, dava pra não gastar)')); sh.appendChild(arrepRow);\n    var det = el('details', 'mais'); if(!novo) det.open = true; var sm = el('summary', null, 'Descrição, conta, data e planilha'); det.appendChild(sm); var dBox = el('div'); det.appendChild(dBox); sh.appendChild(det);\n    dBox.appendChild(campo('Descrição', idesc, 'ldesc'));\n    var g2 = el('div', 'grid2');"),
 ("    g2.appendChild(campo('Data', idt, 'ldata'));\n    sh.appendChild(g2);\n    var arrepRow = el('label', 'switch'); var ca = el('input'); ca.type = 'checkbox'; ca.id = 'larrep'; ca.checked = !!t.arrep; ca.addEventListener('change', function(){ t.arrep = ca.checked; });\n    arrepRow.appendChild(ca); arrepRow.appendChild(document.createTextNode('Me arrependo (besteira, dava pra não gastar)')); sh.appendChild(arrepRow);\n    var orcRow = el('div', 'field');",
  "    g2.appendChild(campo('Data', idt, 'ldata'));\n    dBox.appendChild(g2);\n    var orcRow = el('div', 'field');"),
 ("    orcRow.appendChild(lo); orcRow.appendChild(so); sh.appendChild(orcRow);\n    arrepRow.hidden = t.tipo !== 'gasto'; orcRow.hidden = t.tipo !== 'gasto';\n    var row = el('div', 'row');\n    var save = el('button', 'btn primary wide', novo ? 'Salvar' : 'Salvar alterações'); save.type = 'button'; save.id = 'lsave';\n    save.addEventListener('click', function(){\n      if(!(t.valor > 0)){ toast('Coloca o valor.'); iv.focus(); return; }\n      if(!t.cat){ toast('Escolhe a categoria.'); return; }\n      if(!t.desc) t.desc = catDe(t.cat, t.tipo).n;\n      t.atualizadoEm = new Date().toISOString();\n      var i = -1; FIN.lanc.forEach(function(x, k){ if(x.id === t.id) i = k; });\n      if(i > -1) FIN.lanc[i] = t; else FIN.lanc.push(t);\n      finSave(); closeSheet(); render(); toast(novo ? (t.tipo === 'gasto' ? 'Gasto anotado.' : 'Ganho anotado.') : 'Salvo.');\n      try{ if(navigator.vibrate) navigator.vibrate(10); }catch(e){}\n    });\n    row.appendChild(save); sh.appendChild(row);",
  "    orcRow.appendChild(lo); orcRow.appendChild(so); dBox.appendChild(orcRow);\n    arrepRow.hidden = t.tipo !== 'gasto'; orcRow.hidden = t.tipo !== 'gasto';\n    function salvar(maisUm){\n      if(!(t.valor > 0)){ toast('Coloca o valor.'); iv.focus(); return; }\n      if(t.tipo !== 'transf' && !t.cat){ toast('Escolhe a categoria.'); return; }\n      if(!t.desc) t.desc = t.tipo === 'transf' ? 'Transferência' : catDe(t.cat, t.tipo).n;\n      t.atualizadoEm = new Date().toISOString();\n      var i = -1; FIN.lanc.forEach(function(x, k){ if(x.id === t.id) i = k; });\n      if(i > -1) FIN.lanc[i] = t; else FIN.lanc.push(t);\n      FIN.cfg = FIN.cfg || {}; FIN.cfg.contaPadrao = t.conta;\n      finSave(); closeSheet(); render(); toast(novo ? (t.tipo === 'gasto' ? 'Gasto anotado.' : t.tipo === 'ganho' ? 'Ganho anotado.' : 'Transferência anotada.') : 'Salvo.');\n      try{ if(navigator.vibrate) navigator.vibrate(10); }catch(e){}\n      if(maisUm) setTimeout(function(){ sheetLanc(null, true); }, 260);\n    }\n    var row = el('div', 'row');\n    var save = el('button', 'btn primary wide', novo ? 'Salvar' : 'Salvar alterações'); save.type = 'button'; save.id = 'lsave'; save.addEventListener('click', function(){ salvar(false); });\n    row.appendChild(save); sh.appendChild(row);\n    if(novo){ var mais = el('button', 'btn wide', 'Salvar e lançar outro'); mais.type = 'button'; mais.id = 'lmais'; mais.addEventListener('click', function(){ salvar(true); }); sh.appendChild(mais); }"),
 # txRow: transferencia
 ("  var c = catDe(t.cat, t.tipo), conta = contaDe(t.conta);\n  var b = el('button', 'tx'); b.type = 'button'; b.id = 'tx-' + t.id; b.style.setProperty('--cc', c.c);\n  b.appendChild(el('span', 'ic', c.n.slice(0, 2).toUpperCase()));\n  var d = el('span', 'd'); d.appendChild(el('span', 't', t.desc || c.n)); d.appendChild(el('span', 's', c.n + (conta ? ' · ' + conta.nome : '') + (t.orc ? ' · planilha' : ''))); b.appendChild(d);\n  var v = el('span', 'v ' + (t.tipo === 'ganho' ? 'g' : 'r'), (t.tipo === 'ganho' ? '+' : '−') + fmt(t.valor)); if(t.arrep) v.appendChild(el('small', null, 'besteira')); b.appendChild(v);",
  "  var transf = t.tipo === 'transf', c = transf ? {n:'Transferência', c:'#9A9CBA'} : catDe(t.cat, t.tipo), conta = contaDe(t.conta);\n  var b = el('button', 'tx' + (transf ? ' transf' : '')); b.type = 'button'; b.id = 'tx-' + t.id; b.style.setProperty('--cc', c.c);\n  b.appendChild(el('span', 'ic', transf ? '⇄' : c.n.slice(0, 2).toUpperCase()));\n  var d = el('span', 'd'); d.appendChild(el('span', 't', t.desc || c.n)); d.appendChild(el('span', 's', c.n + (conta ? ' · ' + conta.nome : '') + (t.orc ? ' · planilha' : ''))); b.appendChild(d);\n  var v = el('span', 'v ' + (t.tipo === 'ganho' ? 'g' : transf ? 't' : 'r'), (t.tipo === 'ganho' ? '+' : transf ? '' : '−') + fmt(t.valor)); if(t.arrep) v.appendChild(el('small', null, 'besteira')); b.appendChild(v);"),
 # hero: livre ate o fim do mes + por dia
 ("  if(semDados) hero.appendChild(el('p', 'msg', 'Nada lançado ainda. Toca no + e anota o primeiro gasto. Anotar é o que dá pra cortar.'));",
  "  var orcMes = orcTotal(FIN.orc.ess) + orcTotal(FIN.orc.nao), avulsos = L0.filter(function(t){ return t.tipo === 'gasto' && !t.orc; }).reduce(function(a, t){ return a + (+t.valor || 0); }, 0);\n  if(s.renda > 0 && orcMes > 0){\n    var livre = s.renda - orcMes, resta = livre - avulsos, dias = diasNoMes(fm), hoje = diaHoje(fm), faltam = Math.max(1, dias - hoje + 1), lv = el('div', 'livre');\n    var lb = el('div'); lb.appendChild(el('span', null, resta >= 0 ? 'Livre até o fim do mês' : 'Estourou o livre do mês')); lb.appendChild(el('b', null, (resta < 0 ? '−' : '') + fmt(Math.abs(resta)))); lb.querySelector('b').style.display = 'block'; lb.querySelector('b').style.color = resta >= 0 ? 'var(--good)' : 'var(--bad)'; lv.appendChild(lb);\n    var ld = el('div', 'dia'); ld.appendChild(document.createTextNode(resta > 0 ? fmt(resta / faltam) + '/dia' : 'sem folga')); var ld2 = el('span'); ld2.style.display = 'block'; ld2.textContent = faltam + (faltam === 1 ? ' dia' : ' dias') + ' restantes'; ld.appendChild(ld2); lv.appendChild(ld); hero.appendChild(lv);\n    hero.appendChild(el('p', 'hint2', 'Livre = renda base − planilha (' + fmt(livre) + '). Já foi ' + fmt(avulsos) + ' em avulsos.'));\n  }\n  if(semDados) hero.appendChild(el('p', 'msg', 'Nada lançado ainda. Toca no + e anota o primeiro gasto. Anotar é o que dá pra cortar.'));"),
 ("function renderFinMes(){\n  var s = saude(fm), r = s.r, hero = $('finHero'); hero.textContent = '';",
  "function renderFinMes(){\n  var s = saude(fm), r = s.r, hero = $('finHero'); hero.textContent = ''; var L0 = lancMes(fm);"),
 # categorias: faixa empilhada + ritmo
 ("  var ids = Object.keys(por).sort(function(a, b){ return por[b] - por[a]; }), max = ids.length ? por[ids[0]] : 1;\n  var cb = $('cats'); cb.textContent = '';",
  "  var ids = Object.keys(por).sort(function(a, b){ return por[b] - por[a]; }), max = ids.length ? por[ids[0]] : 1;\n  var stB = $('stackBox'); stB.textContent = '';\n  if(r.gastos > 0){\n    var essV = 0, livV = 0; L.forEach(function(t){ if(catDe(t.cat).g === 'ess') essV += +t.valor || 0; else livV += +t.valor || 0; });\n    var st = el('div', 'stack'); var se = el('span', 'e'); se.style.width = (essV / r.gastos * 100) + '%'; var sl = el('span', 'l'); sl.style.width = ((livV - r.arrep) / r.gastos * 100) + '%'; var sb = el('span', 'b'); sb.style.width = (r.arrep / r.gastos * 100) + '%'; st.appendChild(se); st.appendChild(sl); st.appendChild(sb); stB.appendChild(st);\n    var lg = el('p', 'stack-leg'); [['e', 'Essencial ' + Math.round(essV / r.gastos * 100) + '%'], ['l', 'Livre ' + Math.round((livV - r.arrep) / r.gastos * 100) + '%'], ['b', 'Besteira ' + Math.round(r.arrep / r.gastos * 100) + '%']].forEach(function(x){ var sp = el('span'); var i = el('i'); i.className = x[0] === 'e' ? '' : ''; i.style.background = x[0] === 'e' ? '#6F8CFF' : x[0] === 'l' ? '#3ECF8E' : 'var(--bad)'; sp.appendChild(i); sp.appendChild(document.createTextNode(x[1])); lg.appendChild(sp); }); stB.appendChild(lg);\n  }\n  var prevCat = {}; orcAtivo(FIN.orc.ess.concat(FIN.orc.nao)).forEach(function(o){ prevCat[o.cat] = (prevCat[o.cat] || 0) + (+o.valor || 0); });\n  var diaN = diaHoje(fm), diasN = diasNoMes(fm);\n  var cb = $('cats'); cb.textContent = '';"),
 ("    row.appendChild(el('span', 'nm', c.n));\n    var v = el('span', 'vl', fmt(por[id])); v.appendChild(el('small', null, pct(por[id], r.gastos) + '%')); row.appendChild(v);",
  "    var nm = el('span', 'nm', c.n);\n    if(prevCat[id] > 0 && diaN > 0){ var esperado = prevCat[id] * diaN / diasN, rt = por[id] > prevCat[id] ? 'bad' : por[id] > esperado * 1.15 ? 'mid' : 'ok'; nm.appendChild(el('span', 'ritmo ' + rt, rt === 'ok' ? 'no ritmo' : rt === 'mid' ? 'vai estourar' : 'estourou')); nm.title = 'Planilha: ' + fmt(prevCat[id]) + '/mês'; }\n    row.appendChild(nm);\n    var v = el('span', 'vl', fmt(por[id])); v.appendChild(el('small', null, pct(por[id], r.gastos) + '%')); row.appendChild(v);"),
])
# atalho do icone do app: ?acao=lancar
patch('src/E-resto.js', [
 ("setTab(TABS.indexOf(abrir) > -1 ? abrir : 'hoje');",
  "setTab(TABS.indexOf(abrir) > -1 ? abrir : 'hoje');\ntry{ if(new URLSearchParams(location.search).get('acao') === 'lancar'){ setTab('financas'); setTimeout(function(){ sheetLanc(); }, 150); history.replaceState(null, '', location.pathname); } }catch(e){}"),
])
m = json.loads(rd('manifest.webmanifest'))
m['shortcuts'] = [{"name": "Lançar gasto", "short_name": "Lançar", "url": "./?acao=lancar", "icons": [{"src": "icon-192.v1.png", "sizes": "192x192", "type": "image/png"}]}]
wr('manifest.webmanifest', json.dumps(m, ensure_ascii=False, indent=2) + '\n')
print('patch5 ok')
